
name: Debug

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Github Event
      run: echo "${{ github.event }}"
    - name: Get Month
      run: date +%m
