
name: Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Github Event
      run: echo "${{ github.event }}"
    - name: Get Month
      run: date +%m
