name: Debug

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'browniebroke'
    runs-on: ubuntu-latest

    steps:
    - run: echo "branch = '$GITHUB_REF_NAME'"
    - run: env
