name: PR Target

on:
  pull_request_target:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
