name: PR Target

on:
  pull_request_target:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - uses: octokit/request-action@v2.x
        id: list_runs
        with:
          route: GET /repos/{repository}/actions/runs
          repository: ${{ github.repository }}
          event: pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.list_runs.outputs.data }}
