name: Update Tags

on:
  release:
    types: [released]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make major tag
        run: |
          MAJOR=$(echo ${GITHUB_REF}  | cut -d'.' -f1)
          git tag ${MAJOR}
      - name: Make minor tag
        run: |
          MINOR=$(echo ${GITHUB_REF}  | cut -d'.' -f1-2)
          git tag ${MINOR}
      - name: Push tags
        run: git push origin HEAD:refs/heads/main --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
